/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EntropyERC7984ToERC20WrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "entropyOracle"
      | "erc20Balances"
      | "getEncryptedBalance"
      | "getEntropyOracle"
      | "name"
      | "requestWrapWithEntropy"
      | "symbol"
      | "unwrap"
      | "wrapRequestCount"
      | "wrapRequests"
      | "wrapWithEntropy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Unwrapped" | "WrapRequested" | "Wrapped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc20Balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestWrapWithEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unwrap",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrapRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapWithEntropy",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20Balances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWrapWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrapRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapWithEntropy",
    data: BytesLike
  ): Result;
}

export namespace UnwrappedEvent {
  export type InputTuple = [
    user: AddressLike,
    erc20Amount: BigNumberish,
    encryptedAmount: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    erc20Amount: bigint,
    encryptedAmount: string
  ];
  export interface OutputObject {
    user: string;
    erc20Amount: bigint;
    encryptedAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrapRequestedEvent {
  export type InputTuple = [user: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [user: string, requestId: bigint];
  export interface OutputObject {
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrappedEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedAmount: BytesLike,
    wrappedAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    encryptedAmount: string,
    wrappedAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    encryptedAmount: string;
    wrappedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyERC7984ToERC20Wrapper extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyERC7984ToERC20Wrapper;
  waitForDeployment(): Promise<this>;

  interface: EntropyERC7984ToERC20WrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  erc20Balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEncryptedBalance: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  requestWrapWithEntropy: TypedContractMethod<
    [tag: BytesLike],
    [bigint],
    "payable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  unwrap: TypedContractMethod<
    [
      erc20Amount: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  wrapRequestCount: TypedContractMethod<[], [bigint], "view">;

  wrapRequests: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  wrapWithEntropy: TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "erc20Balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestWrapWithEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unwrap"
  ): TypedContractMethod<
    [
      erc20Amount: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "wrapRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "wrapWithEntropy"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Unwrapped"
  ): TypedContractEvent<
    UnwrappedEvent.InputTuple,
    UnwrappedEvent.OutputTuple,
    UnwrappedEvent.OutputObject
  >;
  getEvent(
    key: "WrapRequested"
  ): TypedContractEvent<
    WrapRequestedEvent.InputTuple,
    WrapRequestedEvent.OutputTuple,
    WrapRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Wrapped"
  ): TypedContractEvent<
    WrappedEvent.InputTuple,
    WrappedEvent.OutputTuple,
    WrappedEvent.OutputObject
  >;

  filters: {
    "Unwrapped(address,uint256,bytes)": TypedContractEvent<
      UnwrappedEvent.InputTuple,
      UnwrappedEvent.OutputTuple,
      UnwrappedEvent.OutputObject
    >;
    Unwrapped: TypedContractEvent<
      UnwrappedEvent.InputTuple,
      UnwrappedEvent.OutputTuple,
      UnwrappedEvent.OutputObject
    >;

    "WrapRequested(address,uint256)": TypedContractEvent<
      WrapRequestedEvent.InputTuple,
      WrapRequestedEvent.OutputTuple,
      WrapRequestedEvent.OutputObject
    >;
    WrapRequested: TypedContractEvent<
      WrapRequestedEvent.InputTuple,
      WrapRequestedEvent.OutputTuple,
      WrapRequestedEvent.OutputObject
    >;

    "Wrapped(address,bytes,uint256)": TypedContractEvent<
      WrappedEvent.InputTuple,
      WrappedEvent.OutputTuple,
      WrappedEvent.OutputObject
    >;
    Wrapped: TypedContractEvent<
      WrappedEvent.InputTuple,
      WrappedEvent.OutputTuple,
      WrappedEvent.OutputObject
    >;
  };
}
